- hosts: preflight
  tasks:
  - import_role:
      name: confluent.preflight
    tags:
      - pre-install
- hosts: schema-registry
  tasks:
  - import_role:
      name: confluent.schema-registry
- hosts: connect-distributed
  tasks:
  - import_role:
      name: confluent.connect-distributed
- hosts: ksql
  tasks:
  - import_role:
      name: confluent.ksql
